# Configuration file for the Sphinx documentation builder.
#
# Generated by ROCm Documentation Generator.
# pylint: disable=invalid-name

# -- Project information ---------------------------------------------------

project = "rocJITsu"
author = "Advanced Micro Devices, Inc."
# pylint: disable=redefined-builtin
copyright = "Copyright (c) Advanced Micro Devices, Inc. All rights reserved."
# pylint: enable=redefined-builtin
# TODO: derive the version from this component's public header (see
# sibling components such as amdsmi or rccl) so the docs render a
# version number. No *_VERSION_MAJOR macro was auto-detected.

# -- General configuration -------------------------------------------------

html_theme = "rocm_docs_theme"
html_theme_options = {"flavor": "rocm"}
html_title = "rocJITsu documentation"
suppress_warnings = ["etoc.toctree"]
external_toc_path = "./sphinx/_toc.yml"
external_projects_current_project = "rocjitsu"
extensions = [
    "rocm_docs",
    "sphinx_design",
    "sphinxcontrib.mermaid",
    "breathe",
]
exclude_patterns = ["README.md"]

# -- Doxygen configuration -----------------------------------------------

# Doxygen XML is pre-generated and committed under doxygen/xml. We use plain
# breathe against that committed output rather than rocm_docs.doxygen, which
# unconditionally re-runs Doxygen at build time and overwrites the committed
# XML with symbol-less output on the RTD builder.
breathe_projects = {"rocJITsu API reference": "doxygen/xml"}
breathe_default_project = "rocJITsu API reference"

# -- Sphinx setup ----------------------------------------------------------


def setup(app):
    """Sphinx setup"""
    return {"parallel_read_safe": True, "parallel_write_safe": True}
